### ISSUE TITLE
Publish on Chrome Store

### ISSUE THREAD

**Issue by danvk** [provegard/LinkToId#1]
This extension is fantastic. I just wish I'd been able to find it last week when I searched for just such a thing on the Chrome store :)

I'm happy to publish it if you're not interested in doing it yourself.

**Comment by provegard** [comment]
Published:

https://chrome.google.com/webstore/detail/linktoid/cggiopngamlojpeoliehhppmdphinjen

**Comment by danvk** [comment]
Nice, congrats! :)
